## Strings

In [ ]:
x = 'This is a String Type in Python'

In [ ]:
# indexing 
print (x[0])
print (x[-1])

In [ ]:
# range
print (x[:4])
print (x[-6:])

In [ ]:
# string basic ops 
# '+' to concate 
# '*' to repeate
first = 'John'
last = 'Doe'
print (first + ' ' + last)
print (first * 4 + ' ' + last * 2)

### Data Files and Summary Statistics

In [ ]:
import csv
%precision 2

In [ ]:
with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

In [ ]:
mpg[:3]

In [ ]:
# keys 'columns' for any row in csv file
mpg[2].keys()

In [ ]:
# values of the record
mpg[2].values()

In [ ]:
# number of records
len(mpg)

In [ ]:
# printing the CSV data 
for rec in range(len(mpg)):
    print (mpg[rec].values())

In [ ]:
# Average of mpg across all cars
sum(float(i['mpg']) for i in mpg)/len(mpg)

In [ ]:
# grouping the cars by number of cylinder, and finding the average cty mpg for each group
cylinders = set(d['cylinders'] for d in mpg)
cylinders # unique level of numbers of cylinders

In [ ]:
yearmodel = [] 
for c in cylinders:
    sumc = 0
    yearcount = 0
    for d in mpg:
        if d['cylinders'] == c:
            yearcount +=1
            sumc += float(d['mpg'])
    yearmodel.append((c,sumc/yearcount))

yearmodel.sort(key=lambda x:x[0])
yearmodel

### Date and Time in Python

In [ ]:
import datetime as dt
import time as tm

In [ ]:
tm.time() # return timestamp/current time in milliseconds since epoch from 1 Jun 1970

In [ ]:
time = dt.datetime.fromtimestamp(tm.time()) # convert timestamp to datetime (year/mon/day hour/min/second)

In [ ]:
time.time()

In [ ]:
time.date()

In [ ]:
# create delta for time operation  -- 20 days ago
delta = dt.timedelta(days=20)
delta

In [ ]:
# get today 
today = dt.date.today()

In [ ]:
today

In [ ]:
today - delta # date from delta(20 days ago)

### functional programming and .map() 

In [1]:
a = [1,2,3,4]
b = [3,4,5,6]
cheep = map(max,a,b)

In [2]:
cheep

In [3]:
for i in cheep:
    print (i)

3
4
5
6


In [12]:
def st(x):
    if isinstance(x,str):
        return True ## most preferred way to check if it's list
    else:
        return False


In [13]:
st("sdsds")

True

In [14]:
string_map = map(st,['1',23,'str'])

In [15]:
for i in string_map:
    print (i)

True
False
True


### Lambda  : for creating anonymouse function 

In [22]:
# lambda must return express
add = lambda a,b : a + b
mul = lambda a,b : a * b
exp = lambda a : a**a

In [18]:
add(2,3)

5

In [25]:
exp(3)

27

In [43]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]
p = lambda person: person.split()[0] + ' ' + person.split()[-1]
#option 1
for person in people:
    print(split_title_and_name(person) == (lambda p: p.split()[0] + ' ' + p.split()[-1])(person))

#option 2
#list(map(split_title_and_name, people)) == list(map(???))

True
True
True
True


In [47]:
list(map(split_title_and_name, people)) == list(map(lambda p: p.split()[0] + ' ' + p.split()[-1], people))

True

### List Comperhension ; condition and loop in one line

In [70]:
# before list comperhension we use for-loop and condition
even = []
for i in range(0,100):
    if i % 2 == 0:
        even.append(i)

In [67]:
print (even)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [62]:
# using list comperhension
evens = [ev for ev in range(0,100) if ev % 2 == 0]

In [68]:
print (evens)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [69]:
even == evens

True

In [75]:
# conver nested loop to list comperhension
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

ttable = [i*j for i in range(10) for j in range(10)]

In [76]:
ttable == times_tables()

True

In [78]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

print (correct_answer[:50])# Display first 50 ids


['aa00', 'aa01', 'aa02', 'aa03', 'aa04', 'aa05', 'aa06', 'aa07', 'aa08', 'aa09', 'aa10', 'aa11', 'aa12', 'aa13', 'aa14', 'aa15', 'aa16', 'aa17', 'aa18', 'aa19', 'aa20', 'aa21', 'aa22', 'aa23', 'aa24', 'aa25', 'aa26', 'aa27', 'aa28', 'aa29', 'aa30', 'aa31', 'aa32', 'aa33', 'aa34', 'aa35', 'aa36', 'aa37', 'aa38', 'aa39', 'aa40', 'aa41', 'aa42', 'aa43', 'aa44', 'aa45', 'aa46', 'aa47', 'aa48', 'aa49']


## Numpy

In [79]:
import numpy as np

In [127]:
# create a list convert it to numpy array 
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [128]:
# multidimensional array -- list of list 
mul = np.array([[1,2,3],[3,4,5],[4,6,6]])

In [129]:
type(mul)

numpy.ndarray

In [130]:
mul.shape

(3, 3)

In [131]:
# generating numbers 
arr = np.arange(0,20,2)
arr

In [138]:
# linspace returns evenly spaced numbers over a specified interval.
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [92]:
arr.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [94]:
arr = np.arange(0,30,2)

In [95]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [97]:
# reshaping array dimensions
arr.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [101]:
y = np.array([4, 5, 6, 3, 4, 5, 6])
y

array([4, 5, 6, 3, 4, 5, 6])

In [102]:
np.diag(y)

array([[4, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0],
       [0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6]])

In [103]:
# create array after evalueate expression
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [126]:
# replicate each elemet x times after each other
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [125]:
# there are ones/zeros/diag "make elements in diagonal" /eye "ones on the diagonal else where is zeros"
p = np.ones([2, 3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [113]:
# append vertically
np.vstack([p,[5,6,7]])

array([[1, 1, 1],
       [1, 1, 1],
       [5, 6, 7]])

In [124]:
# append horizontally
np.hstack([p, [[9],[10]]])

array([[ 1,  1,  1,  9],
       [ 1,  1,  1, 10]])

### 2D arrays

In [144]:
x = np.arange(36)
x = x.reshape((6,6))

In [148]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [153]:
x[:,3:6]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

### Note that sub-array is reference to the original 
#### so make sure you .copy() array before editing the sub array

### Iterating over arrays

In [156]:
test = np.random.randint(0,10,(5,5))
test

array([[7, 4, 4, 2, 0],
       [3, 1, 8, 6, 7],
       [0, 6, 9, 4, 0],
       [8, 7, 4, 4, 7],
       [3, 1, 6, 1, 2]])

In [159]:
for r in test:
    print (r)

[7 4 4 2 0]
[3 1 8 6 7]
[0 6 9 4 0]
[8 7 4 4 7]
[3 1 6 1 2]


In [161]:
len(test)

5

In [166]:
for r in range(len(test)):
    print(test[r])

[7 4 4 2 0]
[3 1 8 6 7]
[0 6 9 4 0]
[8 7 4 4 7]
[3 1 6 1 2]


In [169]:
# for getting the index
for i, r in enumerate(test):
    print ('Row ',i,'> ',r)

Row  0 >  [7 4 4 2 0]
Row  1 >  [3 1 8 6 7]
Row  2 >  [0 6 9 4 0]
Row  3 >  [8 7 4 4 7]
Row  4 >  [3 1 6 1 2]


In [172]:
test2 = test**2
test2

array([[49, 16, 16,  4,  0],
       [ 9,  1, 64, 36, 49],
       [ 0, 36, 81, 16,  0],
       [64, 49, 16, 16, 49],
       [ 9,  1, 36,  1,  4]])

### Iterate through both arrray

In [173]:
zip(test,test2)

In [174]:
zip([1,2,3])

In [183]:
for i, j in zip(test,test2):
    print (i,'+',j, '=',i+j)

[7 4 4 2 0] + [49 16 16  4  0] = [56 20 20  6  0]
[3 1 8 6 7] + [ 9  1 64 36 49] = [12  2 72 42 56]
[0 6 9 4 0] + [ 0 36 81 16  0] = [ 0 42 90 20  0]
[8 7 4 4 7] + [64 49 16 16 49] = [72 56 20 20 56]
[3 1 6 1 2] + [ 9  1 36  1  4] = [12  2 42  2  6]


In [184]:
lambda a : a + 2

<function __main__.<lambda>>

In [185]:
 ['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [186]:
test

array([[7, 4, 4, 2, 0],
       [3, 1, 8, 6, 7],
       [0, 6, 9, 4, 0],
       [8, 7, 4, 4, 7],
       [3, 1, 6, 1, 2]])

In [198]:
test[::7]

array([[7, 4, 4, 2, 0]])

In [202]:
test[:,::1]

array([[7, 4, 4, 2, 0],
       [3, 1, 8, 6, 7],
       [0, 6, 9, 4, 0],
       [8, 7, 4, 4, 7],
       [3, 1, 6, 1, 2]])

In [207]:
np.arange(36).flatten()[::7]

array([ 0,  7, 14, 21, 28, 35])

In [210]:
test = np.arange(36).reshape(6,6)

In [213]:
test

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [215]:
test[2:4,2:4]

array([[14, 15],
       [20, 21]])